name: Subir Nivel Medalhas
on:
  workflow_dispatch: # Permite que você rode manualmente com um clique

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Criar alteração e Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git checkout -b "subir-nivel-${{ github.run_id }}"
          echo "Update: $(date)" >> progresso.txt
          git add progresso.txt
          git commit -m "Upgrade medalhas
          
          Co-authored-by: GitHub <noreply@github.com>"
          git push origin "subir-nivel-${{ github.run_id }}" # Adicionei o push aqui


      - name: Abrir e Mesclar PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Cria o PR e guarda o link
          PR_URL=$(gh pr create --title "Auto Upgrade" --body "Subindo nível das medalhas")
          # Mescla o PR imediatamente
          gh pr merge $PR_URL --merge --admin --delete-branch


