name: Subir Nivel Medalhas
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Criar alteração e Branch
        env:
          MY_EMAIL: "henriquesouzasilva80@gmail.com"
          MY_NAME: "LuizHenrique435"
        run: |
          # Configura sua identidade oficial
          git config --global user.name "$MY_NAME"
          git config --global user.email "$MY_EMAIL"
          
          # Cria branch única para o PR
          BRANCH_NAME="subir-nivel-${{ github.run_id }}"
          git checkout -b "$BRANCH_NAME"
          
          # Altera o arquivo para gerar atividade
          echo "Update: $(date)" >> progresso.txt
          
          git add progresso.txt
          
          # O SEGREDO: Força você como autor e adiciona o coautor
          git commit --author="$MY_NAME <$MY_EMAIL>" -m "Upgrade medalhas
          
          Co-authored-by: GitHub <noreply@github.com>"
          
          git push origin "$BRANCH_NAME"

      - name: Abrir e Mesclar PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Cria o PR e armazena a URL
          PR_URL=$(gh pr create --title "Auto Upgrade" --body "Subindo nível das medalhas")
          # Mescla e limpa a branch
          gh pr merge $PR_URL --merge --admin --delete-branch
