name: Subir Nivel Medalhas
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Criar alteração e Push
        env:
          BOT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          BOT_NAME: "github-actions[bot]"
        run: |
          git config --global user.name "$BOT_NAME"
          git config --global user.email "$BOT_EMAIL"
          
          BRANCH_NAME="feature/melhoria-medalhas"
          
          # Garante que estamos na main para criar a branch nova a partir dela
          git checkout main
          
          # Deleta a branch local se ela já existir para evitar lixo de execuções anteriores
          git branch -D "$BRANCH_NAME" || true
          
          # Cria a branch totalmente nova
          git checkout -b "$BRANCH_NAME"
          
          # Altera o arquivo
          echo "Update: $(date)" >> progresso.txt
          
          git add progresso.txt
          git commit -m "Upgrade medalhas - Manual PR"
          
          # O --force garante que o GitHub aceite a branch nova mesmo que já exista uma lá
          git push origin "$BRANCH_NAME" --force
